### ISSUE TITLE
Add new units specified in addenda 135-2012ar

### ISSUE THREAD

**Issue by Shai-tan** [JoelBender/bacpypes#106]
Add new units specified in addenda 135-2012ar
http://www.bacnet.org/Addenda/Add-135-2012ar.pdf

See attached to this issue a patch that add new unit in EngineeringUnits enumeration.

[Addenda_135-2012ar.txt](https://github.com/JoelBender/bacpypes/files/804429/Addenda_135-2012ar.txt)

**Comment by JoelBender** [comment]
This is in `stage` and ready for the next release.  Thank you!

**Comment by Shai-tan** [comment]
After review, I miss two unit in my previous patch. These unit are from addenda 2012ar too.
See attached patch for details.
[MissingUnit_addenda2012ar.txt](https://github.com/JoelBender/bacpypes/files/1182942/MissingUnit_addenda2012ar.txt)
