### ISSUE TITLE
Sample script that showcases use of bacpypes.app.BIPForeignApplication

### ISSUE THREAD

**Issue by nilstoedtmann** [JoelBender/bacpypes#109]
e.g. 

Phase 1: Discover existence of BACnet/IP devices (instance-id and IP address) with WHOIS broadcasts via a BBMD.

Phase 2: For each BACnet/IP device found, query the its label (objectName of device object) via unicast read_prop.

**Comment by JoelBender** [comment]
There is a new `109-device-discovery` branch with a sample application `DeviceDiscovery.py` applications in it, I'm going to clone this and make it "foreign" to hunt down the `deviceInfoCache` bug.

**Comment by nilstoedtmann** [comment]
Adding `self.smap.deviceInfoCache = self.deviceInfoCache` here https://github.com/JoelBender/bacpypes/blob/master/py27/bacpypes/app.py#L526 solves it for us

**Comment by nilstoedtmann** [comment]
(We can send a pull request, but it's gonna take a while)

**Comment by JoelBender** [comment]
I committed the other sample along with the fix in the `bacpypes.app` module, let me know if it works.

**Comment by nilstoedtmann** [comment]
That should do it. We went ahead with a modified clone of `bacpypes.app.BIPForeignApplication` that has exactly your change, and that worked.

**Comment by JoelBender** [comment]
Merged into stage
