### ISSUE TITLE
Error class return when reading / writing an unknwow property

### ISSUE THREAD

**Issue by Shai-tan** [JoelBender/bacpypes#111]
Error class return when reading / writing an unknwow property seems to be wrong in ReadProperty and WriteProperty services.
In fact, the class specified in standard is "property" for this error. But in bacpypes implementation, the class "object" is replied.

[0004_UnknownPropertyClass.txt](https://github.com/JoelBender/bacpypes/files/841245/0004_UnknownPropertyClass.txt)

**Comment by JoelBender** [comment]
Thank you for the notice an patch, this is in the `111-unknown-property-error-class` branch and I think this is ready to be merged into the next release.

**Comment by JoelBender** [comment]
Merged into stage
