### ISSUE TITLE
DaysOfWeek and EventTransitionBits classes have invalid bitLen value

### ISSUE THREAD

**Issue by karolgil** [JoelBender/bacpypes#121]
bacpypes/basetypes.py

Both objects should have proper bitLen value set.
In case of DaysOfWeek it should be 7.
In case of EventTransitionBits it should be 3.

Regards!

**Comment by JoelBender** [comment]
Good catch!  **Thank you!**  I changed this in `stage` and will be merged into the next release.
```
>>> from bacpypes.basetypes import DaysOfWeek
>>> dow = DaysOfWeek()
>>> print(dow)
BitString(!monday,!tuesday,!wednesday,!thursday,!friday,!saturday,!sunday)
```
Note that if you pass a list of bits `[0,1,0,1]` the bit string will only be as long as you told it to be:
```
>>> dow = DaysOfWeek([0,1,0,1])
>>> print(dow)
BitString(!monday,tuesday,!wednesday,thursday)
```
but if you pass in names it will be the correct length:
```
>>> dow = DaysOfWeek(['wednesday','friday'])
>>> print(dow)
BitString(!monday,!tuesday,wednesday,!thursday,friday,!saturday,!sunday)
```
