### ISSUE TITLE
Method to inquire id of the local B/IP network (WhatIsNetworkNumber/NetworkNumberIs)

### ISSUE THREAD

**Issue by nilstoedtmann** [JoelBender/bacpypes#134]
Implement a method to inquire the id of the local BACnet/IP network, using `WhatIsNetworkNumber` (6.4.19) and processing the `NetworkNumberIs` (6.4.20) response.

----
This is picking up from https://gitter.im/JoelBender/bacpypes?at=598899b5614889d47527e7a8

**Comment by JoelBender** [comment]
I'm bumping this to the next release because the 0.17.0 is already a lot.

**Comment by JoelBender** [comment]
@nilstoedtmann thanks for being patient :smile:

**Comment by JoelBender** [comment]
ready for release
