### ISSUE TITLE
Device Info Cache Reference

### ISSUE THREAD

**Issue by JoelBender** [JoelBender/bacpypes#142]
Each `ClientSSM` and `ServerSSM` instance gets a `DeviceInfo` instance from the cache when it starts its work and releases it when it's done.  The problem is when there is more than one active SSM there could be more than one reference to the same instance and when one SSM calls `release_device_info()` the cache entry was removed, the second SSM call failed.

**Comment by JoelBender** [comment]
Check out the `142-device-info-cache` branch for a patch and additional sample applications.

**Comment by kmonson** [comment]
@JoelBender This fixes our problem with concurrent requests.

**Comment by JoelBender** [comment]
Good!  Thank you.
