### ISSUE TITLE
Event Enrollment: Fault notification

### ISSUE THREAD

**Issue by calligp** [JoelBender/bacpypes#151]
As described in BACnet specification, the event enrollment is linked to the reliability of the object reference reliability. For this purpose a specific notification parameter is defined but not implemented in your library, it is named "ChangeOfReliability" with identifier 19.

I suggest you the patch attached. [0012_ChangeOfReliabilityParameters.txt](https://github.com/JoelBender/bacpypes/files/1527420/0012_ChangeOfReliabilityParameters.txt)

Another minor point regarding the event enrollment object implementation. The property `eventDetectionEnable` is required and not optional.

**Comment by JoelBender** [comment]
Thank you for the patch, I committed it to `stage`.  I'll be back to this issue for the `eventDetectionEnable` part before I close it.

**Comment by JoelBender** [comment]
This kept getting pushed back because it never got assigned to a milestone and I lost track of it.  A thousands pardons!

**Comment by JoelBender** [comment]
Thank you.
