### ISSUE TITLE
Management of BBMD specific requests in simple (and foreign) application server.

### ISSUE THREAD

**Issue by calligp** [JoelBender/bacpypes#166]
For non BBMD device, the annex J of standard specification indicates the server should reply with BVLC result specifying error code.
Concerned services are:
* Write-Broadcast-Distribution-Table
* Read-Broadcast-Distribution-Table
* Register-Foreign-Device
* Read-Foreign-Device-Table
* Delete-Foreign-Device-Table-Entry
* Distribute-Broadcast-To-Network

These services are well managed in `BIPBBMD` class from `bvllservice.py` but not in `BIPSimple` and `BIPForeign`. I added in `confirmation`, the treatment for each of these pdu which sends a static result (with corresponding code). 
See attached patch for implementation details.

[0016_BBMDRequestMngt.txt](https://github.com/JoelBender/bacpypes/files/1707984/0016_BBMDRequestMngt.txt)

**Comment by JoelBender** [comment]
Thank you, this will help pass the conformance tests (Clause 14.1).  I didn't bother with a branch for these, I just committed it to `stage`.
