### ISSUE TITLE
protocolObjectTypesSupported property compliant with certification tests

### ISSUE THREAD

**Issue by calligp** [JoelBender/bacpypes#176]
In certification tests regarding revision 14 of the protocol, the `protocolObjectTypesSupported` property should be a BitString of 55 item. But in current implementation only 50 are defined.

You can find my proposed patch in attachment.

[0022_AddMissingObject.txt](https://github.com/JoelBender/bacpypes/files/1833740/0022_AddMissingObject.txt)

**Comment by JoelBender** [comment]
Thank you, I changed it a little so it uses "programmer friendly" names, and included the new names in `ObjectType` enumeration.

**Comment by calligp** [comment]
Oh yes indeed, name in my patch are not consistent with other. Sorry
