### ISSUE TITLE
Foreign Device / invalid PDU type

### ISSUE THREAD

**Issue by ChristianTremblay** [JoelBender/bacpypes#181]
BAC0, registered as a Foreign Device to a Jace
Sends whois command and response received (validated in Wireshark)
But bacpypes raises a `invalid pdu type` warning....
https://files.gitter.im/JoelBender/bacpypes/oo0v/image.png

Moving OriginalUnicastNPDU condition in bvllservice fixes the issue.

**Comment by JoelBender** [comment]
Merged into `stage` for release.
