### ISSUE TITLE
Optional parameter of confirmed requests

### ISSUE THREAD

**Issue by calligp** [JoelBender/bacpypes#185]
In two confirmed request, I found a difference regarding the optional parameters between bacpypes implementation and the standard:
* `LifeSafetyOperationRequest`
  * The `objectIdentifier` parameter is optional but not in bacpypes implementation
* `RemoveListElementRequest`
  * The `propertyArrayIndex` parameter is optional but not in bacpypes implementation

See attached patch.
[0024_OptionalParameters.txt](https://github.com/JoelBender/bacpypes/files/1972628/0024_OptionalParameters.txt)

**Comment by JoelBender** [comment]
Thank you!
