### ISSUE TITLE
APDU retry mechanisme doesn't send enought message

### ISSUE THREAD

**Issue by calligp** [JoelBender/bacpypes#187]
To prepare the certification test, we test the mechanism of retry apdu when the server generates a confirmed (event or COV) notification. A trouble occurs when the client doesn't send acknowledgement of the notification.

My device is configured with `apduRetry = 3` but the notification is sent only 3 times. The expected number in my point of view is 4 : Initial notification and 3 retry.

I suggest you attached patch to correct this issue.
[0023_ApduRetry.txt](https://github.com/JoelBender/bacpypes/files/1974263/0023_ApduRetry.txt)

**Comment by JoelBender** [comment]
The `187-apdu-retry` branch has the fix and an additional test.  I just realized that it assumes the default retry count is 3, so there should probably be two versions; one that uses the default which is expected to break if the default changes, and one that sets `numberOfApduRetries` and uses that value explicitly.
