### ISSUE TITLE
Foreign device registration?

### ISSUE THREAD

**Issue by erincamille** [JoelBender/bacpypes#200]
Hi,

I have a BACnet device that I would like to register as a foreign device on a BBMD. However, I can't seem to figure out how to get the device to initiate this request. Are there any examples of this? I see that there is a key for a foreignBBMD in the .ini file, but I don't see it used anywhere in the code. 

Thanks for your help!

**Comment by JoelBender** [comment]
Look at the two sample applications **WhoIsIAm.py** and **WhoIsIAmForeign.py** and notice that the only differences are the application class, and that the version that registers itself as a foreign device has the extra parameters.  These are passed from the INI file down through the initialization code to the BVLL layer, compare the `BIPSimpleApplication` with the `BIPForeignApplication`.

**Comment by erincamille** [comment]
Ok, thanks!
