### ISSUE TITLE
Receive response but not catched by BACPypes

### ISSUE THREAD

**Issue by Enderdead** [JoelBender/bacpypes#206]
Hello,
I  just getting started to test some sample code in order to get data from a device working with BACnet/IP.
I using bacpypes-0.17.2.
I tried many sample script like : WhoIAm.py and ReadProperty.py.
In every command (whois, read), i can see with WireShark my request and the response from the target  but BACPypes  didn"t see them.
My IP is : 192.168.2.26 
The Target is : 192.168.2.15
The netmask is : 255.255.255.0

This is my my BACpypes.ini :
```
[BACpypes]
objectName: Betelgeuse
address: 192.168.2.0/24
objectIdentifier: 2000
maxApduLengthAccepted: 1476
segmentationSupported: segmentedBoth
vendorIdentifier: 15
foreignBBMD: 192.168.2.15
foreignTTL: 30

```
In order to illustrate my problem, when I launch this command
 read 192.168.2.15 analogInput 7 presentValue

I can this that in Wireshare

![screenshot_20180627_152901](https://user-images.githubusercontent.com/22777836/41977158-fbb6d130-7a1e-11e8-9447-5c3c0b150143.png)

![screenshot_20180627_152939](https://user-images.githubusercontent.com/22777836/41977177-01ad5faa-7a1f-11e8-984c-07b9ad123a24.png)

Has anyone  can provide some solution about my problem?

Thank's

**Comment by dumbledore-lessorciersweb** [comment]
Hi
I think you have to put on the BACpypes.ini the address of the device and not the network
In your case the address should be 192.168.2.26/24 and not 192.168.2.0/24.

The Foreign address shouldn't be the address of the destination but I don't think this can make the BACpypes not communicate in your case.

**Comment by Enderdead** [comment]
Thank's a lot ! Everything works perfectly.
