### ISSUE TITLE
How to  establish MS/TP connection through RS485 using bacpypes

### ISSUE THREAD

**Issue by dayanand4u** [JoelBender/bacpypes#223]
I would like to test bacnet ms/tp using RS485 using bacpypes python  module. 
Please let me know is bacpypes supports ms/tp if yes could you please share the example.

**Comment by JoelBender** [comment]
BACpypes does not support MS/TP.  There have been discussions about supporting it via a USB dongle where the dongle can take care of the token passing and timing problems.
