### ISSUE TITLE
Example in a non threaded process

### ISSUE THREAD

**Issue by max13fr** [JoelBender/bacpypes#227]
Hello,

I would like to use bacpypes in a non threaded script to get values on a several points of bacnet/ip devices. I would like to write a small module really easy to use, something like that : 

```
local_ip = '1.1.1.1/24'
device_ip = '1.1.1.5'
device_id = 1001
points_list = { 'temp1' => {'type': 'analogValue', 'address': 8}, 'pressure1' => {'type': 'analogInput', 'address': 3} }

import bacnetsimple
device = bacnetSimple.device(local_ip, device_ip, device_id)
result = device.get_values(points_list) # eg: { 'temp1': 24.43, 'pressure': 203.0 }
exit()
```

BAC0 appeared to be really great for my needs, but after trying it during few weeks, I think it would not : 
the philosophy are different. BAC0 tries to achieve a lot of things (pandas, bokeh, flask, flask_bootstrap, lite version, ...) so the project is huge, complex, and really hard to debug and fix (at least for an external developer).
For example, I have a really annoying issue that seems really hard to correct because there is no timeout: https://github.com/ChristianTremblay/BAC0/issues/112

I think the best solution to achieve my goal is to run a bacpypes application with a timeout on the main run() function. If we get the ack we can stop and return the result, if not, we'll stop when the timeout occurs.

You wrote a really great example here : 
https://gist.github.com/JoelBender/a1cadcf8e80488c0c9afb47177a71131

Unfortunatelly, it's only for a single value and there is no timeout. It's that possible to improve this example ?

Thanks in advance,
Best regards, Max

**Comment by JoelBender** [comment]
Check out `samples/MultipleReadProperty.py`, there is a list of things to read at the top, the BACnet address of the object, the object identifier, and the property to read.  There are a number of things a more advanced data gathering application can do, like read the present value of multiple objects in one request if it supported, but this is a good start.

There is a timeout, the `apduTimeout` and `numberOfApduRetries` specifies how long to wait before resending a request, and how many times it should try.  The `LocalDeviceObject` in the `bacpypes.local.device` module has the default values, but you can override these in your INI file or some other way the you want to keep them.  When the request times out the application layer (more specifically the client state machine) will send an Abort up the stack.

Be careful with terminology, the "address" of an object in your example code is called an "instance number".  The fact that BACnet has devices, objects, device objects, device identifiers and device object instance numbers are bad enough!

**Comment by ChristianTremblay** [comment]
A couple users actually told me some stories about situations where a request will hang forever. I haven't been able to reproduce exactly what they were experiencing... wondering what can be related to bad implementation in the device itself... or if it's a bug in the app... 

I can also reference : https://github.com/ChristianTremblay/BAC0/issues/93#issuecomment-407205070

where the user identified the IOCB being "blocked...".

We already talked about the "possible" need for a timeout and the answer was that there was already one (apduTimeout). Does this require special error handling that I would not have coded ?

In BAC0, I use threads for different things like tasks, but all network calls are "deferred" to bacpypes so only one thread deals with the network.

As with any system, intermittent troubles can really be weird and hard to troubleshoot... and we know how many weird devices there is outside !

**Comment by max13fr** [comment]
Thanks for you help to both of you, I'll keep you update.

@ChristianTremblay : don't worry, you did an awesome work with BAC0, I just looking for a different approach that fit my needs. You're help is really precious.
