### ISSUE TITLE
enhancement: do you have or plan to support BACnet Security connection

### ISSUE THREAD

**Issue by henrywah196** [JoelBender/bacpypes#229]
Does Bacpypes support or plan to support BACnet security connection.

**Comment by JoelBender** [comment]
Yes, for _BACnet Secure Connect_ [BACnet/SC](http://www.bacnet.org/Addenda/index.html#2016bj) the plan is to move to `asyncio` with Python 3.6+ and rely on the [websockets](https://github.com/aaugustin/websockets) library for applications that need it.

As for the addenda, there will be at least one more public advisory review draft as developers gain more experience with it and go through another round of plug fest testing.
