### ISSUE TITLE
Simple Application framework with add-in router functionality

### ISSUE THREAD

**Issue by tjohnsonhvac** [JoelBender/bacpypes#231]
I am putting together an application for a router. I am currently using the BIPSimpleApplication as the framework to handle the device and a handful of bacnet values being pulled from the hardware. (cpu, memory, network info, etc.)  I need to add in different router features as well, (IP2IP routing, BBMD, etc.) I see the IP2IP router example, is there a way to pull in the IP2IPRouter class and initialize it properly or should I use the  IP2IPRouter as the framework and add in the device values.

**Comment by JoelBender** [comment]
The IP2IP router example has two BIP mini-stacks (the UDP layer, the Annex J encoder and decoder, and the `BIPSimple`) and one or both of the `BIPSimple` instances can be swapped with a `BIPBBMD` instance. It stops at the networking layer and doesn't have an application layer.  The BIPSimpleApplication has the client/server state machine piece `StateMachineAccessPoint` and the `ApplicationServiceAccessPoint` "above it" in its stack.

The simplest thing would be to clone the `BIPSimpleApplication` as your own, swap `BIPSimple` with `BIPBBMD` instance, and if you need a connection to another network, build a little mini-stack like the "second stack" part of the IP2IPRouter.

The `bind(a,b,c)` function is the "stack builder" that starts at the top with client `a` and server `b` and binds them together, then `b` as a client and `c` as a server, etc.
