### ISSUE TITLE
Unable to perform write request on point object properties of AI/AO/BI/BO

### ISSUE THREAD

**Issue by sandhiya88** [JoelBender/bacpypes#232]

**Comment by sandhiya88** [comment]
Unable to perform write request on point object properties of AI/AO/BI/BO in bacpypes.

I am trying the below command. 
bacnet.write('2002:24 analogInput 10005 presentValue 100') 

gives the error below:
raise NoResponseFromController()
NoResponseFromController

**Comment by JoelBender** [comment]
This library doesn't have an API like that, the closest it has would be to pipe that command into one of the sample applications:
```
$ echo "write 2002:24 analogInput:10005 presentValue 100.0" | python samples/ReadWriteProperty.py
```
Note there is a subtle change in the object identifier notation that has a ':' between the object type and instance number.

**Comment by sandhiya88** [comment]
I tried the command but found that fewproperties are written as only readable in the object.py file and hence, I not able to write to them. Is there any way we can modify them?
