### ISSUE TITLE
No task manager

### ISSUE THREAD

**Issue by appy92** [JoelBender/bacpypes#236]
Hi,
I am trying to use the code of samples/ReadAllProperties.py in my application. In the main code, if I use **two**  deferred(this_application.next_request) one after another, I get error saying "No task manager"

I want to use output of first request and then execute second request accordingly. What can be the solution here? Thank you!

Regards
Apurva

**Comment by JoelBender** [comment]
The `TaskManager` is a singleton class, there is only one instance for the BACpypes application.  You will get this error if you are trying to create a task with a delta, i.e., "do this thing 3 seconds from now" but the task manager instance hasn't been created so it has no concept of "now".

Following the sample, when a request is completed the `complete_request()` callback is executed, so within that function you can create other types of requests and attach callback functions to them.  The iocb object is going to have an `ioResponse` or an `ioError` but not both, and if they are both `None` then there's something else wrong.
