### ISSUE TITLE
None from maxSegmentsAccepted > 64

### ISSUE THREAD

**Issue by elongberg** [JoelBender/bacpypes#238]
(Due to needing segmentation support not yet in the master branch, this comes up when using the [221-server-segmentation](https://github.com/JoelBender/bacpypes/tree/221-server-segmentation) branch, related to issue #221)

While running a bacpypes server, a client with max segments accepted > 64 is attempting a ReadPropertyMultiple. Under the circumstances that the response must be segmented, an error occurs:

```
...
File "/usr/local/lib/python3.5/site-packages/bacpypes/appservice.py", line 835, in confirmation
    if self.segmentCount > self.maxSegmentsAccepted:
TypeError: unorderable types: int() > NoneType()
```
From what I gather, this is a result of apdu.py encoding/decoding max segments > 64 as None.

I might suggest a fix of having _max_segments_accepted_encoding in apdu.py have a special (e.g. -1) value at index 7 instead of None, and checking for that case in appservice.py. Theoretically, we may still need more segments than they support (e.g. we need 100 segments, but they only support 99), but I'm not sure that anything better could be done without actually knowing the exact amount they support.

**Comment by JoelBender** [comment]
The intent was that 7 was similar to "unspecified" that the application doesn't know.  The end result in both 0 and 7 cases is coming to the conclusion that whatever number of segments you have is acceptable, right?  So the check can be:

```
    if (self.masSegmentsAccepted is not None) and (self.segmentCount > self.maxSegmentsAccepted):
        if _debug: ServerSSM._debug("    - client can't receive enough segments")
        abort = self.abort(AbortReason.apduTooLong)
        self.response(abort)
        return
```

Reading the maxSegmentsAccepted property would be the definitive value to use, and in theory the device information "cache" would have that if the application went the extra step to read it before using services that can take advantage of it.
