### ISSUE TITLE
RandomAnalogValueSleep

### ISSUE THREAD

**Issue by bbartling** [JoelBender/bacpypes#239]
Hello,

This maybe a Niagara Workbench issue... But would you happen to know why my Betelgeuse controller goes offline right away? It always comes up on a discovery but goes offline with fault code high lighted yellow:

![image](https://user-images.githubusercontent.com/29737117/51501030-e6249300-1d95-11e9-865d-2dddd6d279be.png)

**Comment by JoelBender** [comment]
No, there's a bug someplace.  Run your application with `--debug bacpypes.core` and see if there's an exception it's catching and dropping it.

**Comment by bbartling** [comment]
Hi Joel,

So with debug enabled, running the script before a BACnet discovery:
![image](https://user-images.githubusercontent.com/29737117/51564082-d7041a80-1e53-11e9-81c9-6ac3e2e62803.png)

Then making a discovery:
![image](https://user-images.githubusercontent.com/29737117/51564110-e97e5400-1e53-11e9-9d74-c33ef1f41090.png)

And then adding the BACnet device to the network, Betelgeuse is offline instantly.
![image](https://user-images.githubusercontent.com/29737117/51564180-264a4b00-1e54-11e9-8cf3-07f76f2b14ef.png)

![image](https://user-images.githubusercontent.com/29737117/51564226-42e68300-1e54-11e9-83af-c0c66e130a4e.png)


Im running a separate PC on Linux Mint 18.3 and using the Niagara workbench tool on a separate Windows laptop. Please let me know if there is anything I should do differently running the script. Thank you so much for creating such a cool tool!

Ben

**Comment by ChristianTremblay** [comment]
Does it react the same if you start a BAC0 instance and discover it with N4
?

If not, something is missing in your code.

Import BAC0
bacnet = BAC0.lite()

Should be enough for the test.

Le mar. 22 janv. 2019 à 15:46, bbartling <notifications@github.com> a
écrit :

**Comment by bbartling** [comment]
BAC0 seems to be working just fine thru N4 discovery... Can BAC0 be used to share a value to a Niagara 4 system? IE, like a calculation in Python share it to the building automation system?

Sorry, Im outwrite confessing I am not a software engineer testing my BACnet creations ;) but a BAS technician experimenting with Python DIY computer vision project


![image](https://user-images.githubusercontent.com/29737117/51566652-bee3c980-1e5a-11e9-9dd3-6612d3618ae4.png)
![image](https://user-images.githubusercontent.com/29737117/51566668-ce631280-1e5a-11e9-9865-8217d74fdc30.png)

**Comment by bbartling** [comment]
Would you have any tips for trouble shooting BAC0 going offline to Niagara? Are there any tuning parameters or firewall issues on a PC that would make BAC0 go offline?


Its offline in Niagara but thru the console it looks fine:

![image](https://user-images.githubusercontent.com/29737117/51566847-50533b80-1e5b-11e9-90ec-e58cd41b0076.png)

**Comment by jscott3201** [comment]
What’s the fault status in Niagara reading on the offline. Console logs
from the platform? Niagara by default uses polling and if it can respond
fast enough it may fault out. Using actions > Ping on the device might
bring it back up.

**Comment by bbartling** [comment]
Here's a platform screenshot. It looks like BAC0 is just a transaction timeout.. Can polling adjustment fix that? Pinging didn't bring anything back to life either...

Not sure about the Betelgeuse error shown before BAC0
![image](https://user-images.githubusercontent.com/29737117/51567375-a8d70880-1e5c-11e9-8ada-481e61671b11.png)

**Comment by jscott3201** [comment]
Something wrong in your device setup code. If I recall correctly pings
check the Device Type (8?). Top error shows it can’t decide the property
correctly. Last Ok time being bull shows it never really pulled the device
in properly. Device pulls in successfully to Niagara the Last Ok Timestamp
should be filled.

**Comment by bbartling** [comment]
@jscott3201, are you referring to BAC0 or BACpypes where I may have something setup/configured wrong? Thanks

**Comment by jscott3201** [comment]
BACpypes side likely. Repo or snippet of your code and .ini file? Most
device props get set off ini file I believe.

**Comment by bbartling** [comment]
In the bacpypes/samples directory I am working with running the RandomAnalogValueSleep.py

![image](https://user-images.githubusercontent.com/29737117/51567934-146da580-1e5e-11e9-973c-670d316eae89.png)


There is also another INI with a ~ 
-sorry I don't know the difference but they look almost exactly the same
![image](https://user-images.githubusercontent.com/29737117/51567963-2bac9300-1e5e-11e9-9705-37832b364553.png)

**Comment by jscott3201** [comment]
I’m on the Subway but the sound of the sample name may be the giveaway
here. If that Value Sleep code is calling core.sleep(), it’s putting the
python thread to sleep which means the server is technically offline and
can’t respond to the messages. I’ll peek at the sample and post if I see
that line. core.run() starts the BACnet python thread which is your device
BAC0 in this case.

**Comment by jscott3201** [comment]
This line: # sleep a little
        time.sleep(args.sleep)

Not sure off quick glance but that might be putting the thread to sleep. Pass in 60s for that CLI argument. Might keep it awake enough to verify that is the cause on the N4 side.

**Comment by JoelBender** [comment]
The sleep time defaults to 100ms to slow things down _a little_, like it's a low powered device on a small network with hardly enough spare CPU cycles to maintain the correct time.  You can gradually increase that time, we have some virtual devices in a gateway that then communicates over 900MHz radio links where the response time can be more than that, but it's pretty rare.

Passing 60 _seconds_ means that whenever the present value of one of its Analog Value Object's the application will be locked up doing nothing.  Requests will get backlogged, multiple attempts will be made, and as you've seen, most clients will give up.  Some will give up a little and try again by themselves, some will give up until you tell them to try again with a supervisory command/interface.

If there was a separation between the application layer processing requests and the communications layer for sending/receiving traffic, then in theory the communications could abort with a **DEVICE_BUSY** error code (Clause 18.1 Error Class - DEVICE).

**Comment by JoelBender** [comment]
@jscott3201 That sample application doesn't use any threads, the `sleep()` call stops everything.  On a busy network the OS layer UDP socket buffer will fill up an it will start dropping packets.  Thank you and @ChristianTremblay for picking up the conversation.

**Comment by ChristianTremblay** [comment]
Running a local N4 station (4.6), I've imported 2 different BAC0 devices, one running on ubuntu, another one on RPi... 
Online, no problem.
Wireshark is clean... 

Bacpypes 0.17.6 and 0.17.5

![capture](https://user-images.githubusercontent.com/6376327/51579818-59aacb00-1e90-11e9-8138-d2f44928b3c1.JPG)

I've simply imported some string points...
![capture2](https://user-images.githubusercontent.com/6376327/51579969-e6558900-1e90-11e9-9295-828bee711d7d.JPG)

Niagara4 BACnet IP configuration
![capture_bacnet](https://user-images.githubusercontent.com/6376327/51580081-40564e80-1e91-11e9-90c5-715ae61a63ff.JPG)

In 2 different subnets as you can see, no BBMD as the Jace will unicast the manually added device in the other subnet.

So if BAC0 is failing on your side, it's probably a network OR a Niagara issue.
If using a custom bacpypes, there is a parameter somewhere.

Disclaimer : Using BAC0 here only as it is a lego app built with a bunch of examples of bacpypes. Any bacpypes should behave the same if configured in a similar way.

**Comment by bbartling** [comment]
Thanks for the help all, I think I am doing something wrong in Bacpypes. I installed BAC0 on raspberry pi and its working just fine how @ChristianTremblay is demonstrating above with the N4 integration..
