### ISSUE TITLE
Run time Error in whoIsIAm.py

### ISSUE THREAD

**Issue by Saravan95** [JoelBender/bacpypes#274]
web~/Downloads/bacpypes-master$ python WhoIsIAm.py
Traceback (most recent call last):
  File "WhoIsIAm.py", line 202, in <module>
    main()
  File "WhoIsIAm.py", line 172, in main
    args = ConfigArgumentParser(description=__doc__).parse_args()
  File "/usr/local/lib/python2.7/dist-packages/bacpypes/consolelogging.py", line 220, in parse_args
    raise RuntimeError("INI file with BACpypes section required")
RuntimeError: INI file with BACpypes section required

Need help
Thank you in Advance

**Comment by JoelBender** [comment]
When you clone the repository there is a file in the root directory called [BACpypes~.ini](https://raw.githubusercontent.com/JoelBender/bacpypes/master/BACpypes~.ini), make a copy of the file and edit it to your local device settings.  The `objectName` is the name of your device, the `address` is the IPv4 address in CIDR notation, and the `objectIdentifier` is the instance number of your device object, also known as the "device instance number".  The `foreignBBMD` and `foreignTTL` are used for foreign device registration, which you probably won't need right away.

**Comment by JoelBender** [comment]
By default the applications look in the current directory for the INI file, but most of them also take an `--ini` option which can point to the file, and in some cases it's easier to set an environment variable, so `BACPYPES_INI` can reference it.
