### ISSUE TITLE
RuntimeError: INI file with BACpypes section required

### ISSUE THREAD

**Issue by praveengowda1** [JoelBender/bacpypes#285]
Hi, @JoelBender sir, im trying to run the ReadProperty.py file and i encountered with an error like
raise RuntimeError("INI file with BACpypes section required")
RuntimeError: INI file with BACpypes section required
can you plz help me with this , im not able to understand the INI files And how to use them

**Comment by JoelBender** [comment]
The INI file is a collection of configuration settings in a text file.  The file format itself is from a long time ago in a galaxy far away, and [Wikipedia](https://en.wikipedia.org/wiki/INI_file) has a good description of the format itself.  The repository comes with a sample file called **BACpypes~.ini** which you can make a copy, call it **BACpypes.ini**, and change it to your local settings.  That is the "default" configuration file name and it is expected to be in the "current directory" of the running application.  There is no "path" concept, like looking in the current directory, then a home directory, then a system directory, etc.

Almost all of the applications take an `--ini` option that takes a file name so you can have lots of these files with different combinations of settings and they can be located anywhere you would like.
