### ISSUE TITLE
How to write command in BACpypes and send to YABE as control signal?

### ISSUE THREAD

**Issue by julia-tech** [JoelBender/bacpypes#291]
Hi,

I would like to write my own control logic, for example, I can run a python code in BACpypes and send the result to YABE to present, e.g. the set point should be on / off. 

How to write code in BACpypes and send to YABE to perform?

Thanks,
Julia

**Comment by JoelBender** [comment]
I think you want to make a values in your application available for YABE to "pull" it via *Read Property* or *Read Property Multiple*, or maybe YABE can issue a Change-of-Value subscription so your application send out a notification when it changes (I don't know if YABE supports COV).  You could send a *Write Property* or *Write Property Multiple* to YABE for each value you want to send, but that's unusual.

I wrote a [sample application](https://raw.githubusercontent.com/JoelBender/bacpypes/a1d51ab383f742fa486ba0bc2c506bf8deab8138/samples/mini_device.py) that should get you started and will be in the next release.  If you have more questions please create another issue.
