### ISSUE TITLE
How to get the connection with WebCTRL?

### ISSUE THREAD

**Issue by julia-tech** [JoelBender/bacpypes#310]
I tried to use the same code (https://github.com/JoelBender/bacpypes/blob/master/samples/HandsOnLab/Sample4_RandomAnalogValueObject.py), however, it is very complicated client. I use the same procedure, but when I use 'WHOIS-IAM' first, it cannot detect the ip-address of the webCTRL. 

Is there any steps that need to make for WebCTRL to send 'WHOIS' first?

Thanks,
Julia

**Comment by JoelBender** [comment]
As I wrote in the other issue, this sample application is a server, not a client, and there is no mechanism in that code for sending requests, so I think you are confusing two different samples.  For WebCTRL, your device running this code would probably consider this a "third party device" and [this document](http://www.automatedlogic.com/SpecSheets/WC_Integrations.pdf) would apparently like you to talk to your dealer.
