### ISSUE TITLE
Python 3.8 Support

### ISSUE THREAD

**Issue by MichaelBMiner** [JoelBender/bacpypes#313]
Hello,

 I was just wondering when will BACpypes support an install with pyton 3.8?

**Comment by JoelBender** [comment]
I have heard of people that say it works fine on 3.8 now.  You can add a `(3, 7): 'py34',` line to the `setup.py` file if you would like to test it.

**Comment by MichaelBMiner** [comment]
I have 3.8 installed and see no issues, but when trying to do a fresh install of bacpypes with 3.8, then bacpypes reports a failure.

**Comment by JoelBender** [comment]
Maybe the `setup.py` application could check for a `--source-folder` option which bypasses the version check?  Meh.  The `bacpypes3` package will be one directory and Python3.6+ anyway.  I fixed the "add this line" comment above, may be that will be good enough for a while.
