### ISSUE TITLE
Cancelling a SubscribeCOVRequest

### ISSUE THREAD

**Issue by noenthu** [JoelBender/bacpypes#316]
Is there a way to cancel SubscribeCOVRequest midway through its lifetime?

**Comment by JoelBender** [comment]
**Clause 13.14.1.1.4** ... If both the 'Issue Confirmed Notifications' and 'Lifetime' parameters are absent, then this shall indicate a cancellation request.

**Comment by noenthu** [comment]
@JoelBender sending a SubscritpionCOV Request with no lifetime or issueConfirmedNotification attribute seems to work.
Sending a False with no lifetime returns an ioError.

**Comment by JoelBender** [comment]
Correct, there are combinations of service parameters that are invalid.
