### ISSUE TITLE
Enumerated Keylist in primitivedata uses dict_items.sort which no longer works in python 3.x

### ISSUE THREAD

**Issue by jklarson** [JoelBender/bacpypes#323]
in bacpypes.py34.bacpypes.primitivedata:

> def keylist(self):
>         """Return a list of names in order by value."""
>         items = self.enumerations.items()
>         items.sort(lambda a, b: self.cmp(a[1], b[1]))

Sort function no longer works in Python version 3.x, should be converted to "sorted"

**Comment by JoelBender** [comment]
I thought it was a problem with the way the key/lambda parameter was provided, but it's because `items()` no longer returns an array, it's an instance of `<class 'dict_items'>`.  Thank you.

**Comment by JoelBender** [comment]
I added this to the 0.18.1 milestone so I don't forget to mention it in the release notes!
