### ISSUE TITLE
Call to ReadForeignDeviceTableAck.bvlpdu_contents() will fail.

### ISSUE THREAD

**Issue by stefanbursuc** [JoelBender/bacpypes#324]
Call to ReadForeignDeviceTableAck.**bvlpdu_contents**() will fail as **FDTEntry** class does not have the **dict_contents**() function.

**Comment by stefanbursuc** [comment]
I have proposed a fix with the pull request #325 .

**Comment by JoelBender** [comment]
Thank you.
