### ISSUE TITLE
Typo in EventParameterAccessEventAccessEvent?

### ISSUE THREAD

**Issue by ottobackwards** [JoelBender/bacpypes#346]
https://github.com/JoelBender/bacpypes/blob/master/py34/bacpypes/basetypes.py#L2199

I don't think sequenceevents is right, I think it should be sequenceElements.  
I cannot create an instance of this class.

**Comment by JoelBender** [comment]
You're correct, and the context value was wrong as well.  This has been fixed and merged into the `develop` branch and will be in the next release.  Thank you!

**Comment by JoelBender** [comment]
There is a simple test application [here](https://gist.github.com/JoelBender/5ddb15970d5ea1d0dd7926e5dfb9ca61) that creates, encodes, and decodes one of these beasts, so it should be all set.
