### ISSUE TITLE
How to set   eventTimeStamps=[TimeStamp,TimeStamp,TimeStamp]

### ISSUE THREAD

**Issue by JimitD** [JoelBender/bacpypes#362]
Hi Joel, 

I am trying to include eventTimeStamps property for Object but unable to set the TimeStamp. 

Which TimeStamp format I should use? I tried following, 

`dtt = DateTime(date=Date().now().value, time=Time().now().value) `

it gave me error of "TimeStamp" required.

**Comment by JoelBender** [comment]
You're close, `TimeStamp` is a choice between three elements and you have to tell it which one:
```
>>> current_date = Date().now()
>>> current_time = Time().now()
>>> current_datetime = DateTime(date=current_date, time=current_time)
>>> current_timestamp = TimeStamp(dateTime=current_datetime)
```
You could also specify the sequence number:
```
>>> other_timestamp = TimeStamp(sequenceNumber=12)
```
