### ISSUE TITLE
Write property description with spaces

### ISSUE THREAD

**Issue by mosterme1003** [JoelBender/bacpypes#384]
When I write a text with spaces to the description property I get an error because the spaces indicate more than one argument for the property value. Is there a way to fix this?

```
bacnet = BAC0.connect(ip=ipLocal)
bacnet.write('192.168.178.10 analogInput 1 description test text')
```
```
File "E:\Python\lib\site-packages\BAC0\core\io\Write.py", line 88, in write
    iocb = IOCB(self.build_wp_request(args, vendor_id=vendor_id))
  File "E:\Python\lib\site-packages\BAC0\core\io\Write.py", line 200, in build_wp_request
    obj_type, obj_inst, prop_id, value, priority, indx = self._parse_wp_args(args)
  File "E:\Python\lib\site-packages\BAC0\core\io\Write.py", line 131, in _parse_wp_args
    indx = int(args[4])
ValueError: invalid literal for int() with base 10: 'text'
```

**Comment by JoelBender** [comment]
This is an issue for [BAC0](https://gitter.im/ChristianTremblay/BAC0), I don't see an easy way to cross post this to a different project, so please create a new issue.

**Comment by JoelBender** [comment]
@ChristianTremblay - note to you - incoming!

**Comment by mosterme1003** [comment]
Sorry, I think I got confused with your repos. I wanted to create this issue in BAC0 in the first place.

**Comment by ChristianTremblay** [comment]
For reference....as the answer I pretty close to bacpypes 
https://github.com/ChristianTremblay/BAC0/issues/246
