### ISSUE TITLE
Move Documentation

### ISSUE THREAD

**Issue by JoelBender** [JoelBender/bacpypes#43]
Move the Sphinx documentation from SourceForge.

**Comment by JoelBender** [comment]
This is going to be put in a persistent **doc** branch.  Similar to **samples** branch, I want to be able to update the documentation regularly.  Of course when there is a new release, the release notes will be updated, and then the **doc** branch will be merged into the master.  I don't expect that it will be important enough to merge the doc branch into staging, which isn't to say that there won't be documentation changes that are a necessary part of closing issues.

**Comment by ChristianTremblay** [comment]
I think we should use the gh-pages branch for doc as it will auto-populate the Web page.

**Comment by JoelBender** [comment]
Ah!  I didn't see your idea.  Well, that's something to consider, but the current documentation is already in reStructuredText, and it synchronizes nicely with ReadTheDocs and gets its own URL: http://bacpypes.readthedocs.org/en/latest/
