### ISSUE TITLE
Check if device is a BBMD

### ISSUE THREAD

**Issue by mosterme1003** [JoelBender/bacpypes#446]
Hi there! Is there a way to check if a specific device in a subnet is configured as a BBMD? I found some classes and methods in your sample and test files that could probably do this job but I simply don't know where to start and how to run this files properly. Can you help me with that?

**Comment by JoelBender** [comment]
Yes, you are looking for an application that can send a `ReadBroadcastDistributionTable` request message to an IPv4 and see if you get an Ack or an Error back.  The sample applications are network layer and application layer, but there aren't any that are for this virtual link layer.  I'll put an example together for reading the BDT and FDT shortly.

**Comment by JoelBender** [comment]
Check out the sample application.

**Comment by mosterme1003** [comment]
First of all, thank you very much! Your sample application works fine. Now I want to implement reading the BDT in one of my own applications without the console. I tried to call the `ReadBroadcastDistributionTable` request just like I would call a `ReadPropertyRequest` for example. Maybe this is already a mistake. It returns a `TypeError('APDU expected')`. Could you help me with that?

And is it also possible to configure a device as a BBMD by calling the `WriteBroadcastDistributionTable` request?

```py
def read_bdt(self, bacnet, deviceIp, timeout=10):
    try:
        request = ReadBroadcastDistributionTable(destination=Address(deviceIp))
        
        iocb = IOCB(request)
        iocb.set_timeout(timeout)
        bacnet.this_application.request_io(iocb)
        iocb.ioComplete.wait()
        
        print("iocb completion event set: %r" % (iocb.ioComplete.is_set(),))
        print("iocb successful: %r" % (iocb.ioState == COMPLETED,))
        print("iocb response: %r" % (iocb.ioResponse,))
        print("iocb aborted: %r" % (iocb.ioState == ABORTED,))
        print("iocb error: %r" % (iocb.ioError,))
        
    except Exception as error:
        print(("exception: {!r}".format(error)))
```
