### ISSUE TITLE
Read FDT method doesn't resolve FDTEntry object

### ISSUE THREAD

**Issue by mosterme1003** [JoelBender/bacpypes#452]
Hey, when I try to read a device's FDT with your ReadWriteBBMD.py sample it returns the FDTEntry object instead of the foreign device's IP address.

`bvlciFDT = [<bacpypes.bvll.FDTEntry object at 0x00000281F8B3E748>]`

Would you like to shortly add the functionality resolving this object and show the wanted IP address like in the ReadBDT method? Thank you in advance!

**Comment by JoelBender** [comment]
The contents are in there, you can tell the debugging output to go into more details about the contents of the PDU by adding this line:
```python
ReadForeignDeviceTableAck._debug_contents = ('bvlciFDT++',)
```
I made that the default.
