### ISSUE TITLE
BACnet server: Help implementing COV for multiple binaryinput

### ISSUE THREAD

**Issue by KlausHammer** [JoelBender/bacpypes#459]
Hi,

From looking at the example "Sample4_RandomAnalogValueObject.py", I have implemented a BACnet server with a total of 256 binaryinput objects where the value is read from a global list (globalvar.alivebits)

I create the object like this in my main function:

```python
# Create alive binary objects
j = 1
for i in range(1, (int(len(globalvar.alivebits)/2))+1): #As we create two objects per module we only need to loop though half the size of alivebits
	j -= 1
	for y in range (1,3):
		j += 1
		aliveBinObject = CustomBinaryInputObject(
			objectIdentifier=('binaryInput', i+j-1),
			objectName='Modul-%d Alivebit-%d' % (i,y),
			)
		_log.debug("    - aliveBinObject: %r", aliveBinObject)
		this_application.add_object(aliveBinObject)
```
Which creates two binaryinput for each module i have connected. 

And when a value is requested from a client, i respond by reading the objectIdentifier like this:

```python
class BinaryInputProperty(Property):
	def __init__(self, identifier):
		if _debug: BinaryInputProperty._debug("__init__ %r", identifier)
		Property.__init__(self, identifier, Integer, default=0, optional=True, mutable=False)

	def ReadProperty(self, obj, arrayIndex=None):
		if _debug: BinaryInputProperty._debug("ReadProperty %r arrayIndex=%r", obj, arrayIndex)
		if _debug: BinaryInputProperty._debug("objectName %r", obj.objectName)

		# access an array
		if arrayIndex is not None:
			raise ExecutionError(errorClass='property', errorCode='propertyIsNotAnArray')

		# sort after each object number to return the correct value from the array
		if _debug: BinaryInputProperty._debug("objectnumber %r", obj.objectIdentifier[1])
		return int(globalvar.alivebits[obj.objectIdentifier[1]-1])
```

All of this works, and I’m now trying to implement COV for alle the inputobjects, but I’m having a bit of trouble figuring out how to do so.

Looking at "/samples/COVServer.py"  it seems like you are simply updating the value of the object with "test_av.presentValue = next_value", and is not actually implementing anything for COV service other than adding "ChangeOfValueServices" to the application class. 
How can i do that as all my binaryinput objects are named the same "aliveBinObject", should i then name them differently like aliveBinObject_0, aliveBinObject_1, aliveBinObject_2 ...  and so forth for each object i create, or can I call something like 

```python
for i in range (int(len(globalvar.alivebits)))
	aliveBinObject.objectIdentifier[1] = i
	if (globalvar.alivebits[i] != old_globalvar.alivebits[i]):
		aliveBinObject.presentValue =  globalvar.alivebits[i]
```
so I can differentiate the objects and just loop though every value in the list to check if any change has happened, or is there another way to do it?

Any help will be very much appreciated

**Comment by JoelBender** [comment]
> ...other than adding "ChangeOfValueServices" to the application class.

Correct, and that service requires that objects have the magic property `_object_supports_cov` set and some criteria to back it up.  For your binary input objects, it's the `GenericCriteria`.  Subclasses of `BinaryInputObject` will already have that set, so you should be good to go.

> ...and is not actually implementing anything for COV service...

The magic, such as it is, is in response to a subscription request where the server adds a "monitor" to the presentValue and binds that to the client.  When `some_object.presentValue = 75.3` is executed, each of the monitoring pieces wake up and see if the criteria matches enough to send a notification.

> How can i do that as all my binary input objects are named the same "aliveBinObject" ...

Your objects already have unique names and identifiers, so they aren't quite the same.  Keeping an array of all of the objects that you create after you have created them like `my_bin_objects.append(aliveBinObject)` is fine, or maybe a dictionary of them that is keyed by some other identifier like `my_bin_objects[i+j-1] = aliveBinObject` or even `my_bin_objects[aliveBinObject.objectName] = aliveBinObject` would also work.

To update the value and send out notifications for subscribers you end up with something simple like:
```python
my_bin_objects[x].presentValue = "active" if y else "inactive"
```

**Comment by KlausHammer** [comment]
Wow, that was easy and straightforwards to do.

Thank you very much for your help :)
