### ISSUE TITLE
asyncore removed from python 3.12

### ISSUE THREAD

**Issue by Mathadon** [JoelBender/bacpypes#505]
Python 3.12 has been released on October 2nd. This version removed the `asyncore` module, which has been deprecated since python 3.6. This means bacpypes no longer works on python 3.12.

Would it be possible to update the implementation of bacpypes accordingly?

See python release notes:
https://docs.python.org/3/whatsnew/3.12.html?highlight=asyncore

**Comment by bbartling** [comment]
Can you switch over to bacpypes3?

**Comment by bbartling** [comment]
Its the new asyncio project: https://github.com/JoelBender/BACpypes3

**Comment by Mathadon** [comment]
Oh I had no clue! 

I checked @JoelBender 's profile but it's not in the listed repositories:
![image](https://github.com/JoelBender/bacpypes/assets/5970879/f76104f3-e42e-46aa-b9b9-94ac6046cab5)


I'll have a look at that, thanks!
