### ISSUE TITLE
Issue in dockerising an MSTP application using Misty and BACpypes

### ISSUE THREAD

**Issue by parthgoel06** [JoelBender/bacpypes#506]
I am getting the below error (**Bus error (core dumped)**) whenever I am trying to start an MSTP application from inside a docker container (using python:3.8 image). This machine is an RPi running Bullseye image with Python 3.9 by default (hence the reason to dockerise).
<img width="408" alt="Screenshot 2023-10-05 at 2 35 22 AM" src="https://github.com/JoelBender/bacpypes/assets/43048193/c20d91cb-feaa-4075-9b64-db61db0fa56d">

The same doesn't happen when I run the MSTP application on the host system (outside the Docker container) of an RPi running Buster image with Python 3.7.
<img width="415" alt="Screenshot 2023-10-05 at 2 39 33 AM" src="https://github.com/JoelBender/bacpypes/assets/43048193/6a7e8572-e902-40b6-b708-93ebb5b3593f">

P.S. I am running the container in privileged mode and have given it the access to use the USB port for MSTP application.

**Comment by JoelBender** [comment]
This is a problem inside misty, I can't help with it, please open an issue [there](https://github.com/riptideio/misty/issues) and mention me so I can track it.
