### ISSUE TITLE
Dependency asyncore has been removed in python 3.12.

### ISSUE THREAD

**Issue by davidwebber** [JoelBender/bacpypes#516]
Python dependency asyncore has been removed in python 3.12.

https://docs.python.org/3.11/library/asyncore.html

`  File "/usr/local/lib/python3.12/site-packages/bacpypes/event.py", line 7, in <module>
    import asyncore
ModuleNotFoundError: No module named 'asyncore'
`

**Comment by JoelBender** [comment]
Correct, you need to switch over to [BACpypes3](https://github.com/JoelBender/bacpypes3) which is rewritten for asyncio, and most of the functionality is easier to use like `await app.read_property(...)` rather than IOCBs, custom timers, etc.

**Comment by davidwebber** [comment]
Great, thank you!
