### ISSUE TITLE
ReadPropertyMultiple Array Content

### ISSUE THREAD

**Issue by JoelBender** [JoelBender/bacpypes#67]
When a ReadPropertyMultple request has been received for a property that is an array, the response should contain the contents of the array, not the length.  It seems to behave like the default value of the array index is zero someplace.  See related conversation [on Google+](https://plus.google.com/b/100756765082570761221/100756765082570761221/posts/bK1KXPiDUmH).

**Comment by ChristianTremblay** [comment]
Still an issue ?

**Comment by JoelBender** [comment]
I posted a follow-up comment on the thread, if this can be reproduced then we'll start a new issue.
