### ISSUE TITLE
Split atomic file services into a separate module

### ISSUE THREAD

**Issue by JoelBender** [JoelBender/bacpypes#87]
There pieces of the atomic read/write file services that are scattered around in the `app` module and sample applications.  Unify the service side into a `service` module.

See the [Service Subpackage](https://sourceforge.net/p/bacpypes/mailman/message/35015580/) topic in the mailing list.

**Comment by ChristianTremblay** [comment]
See issue-87

**Comment by ChristianTremblay** [comment]
As this include iocb, API change + services, maybe the issue could be renamed ?

**Comment by ChristianTremblay** [comment]
This feature brings really big changes to the API.
Documentation updates have been incorporated into this issue (instead of working in a specific "doc" branch. Those doc updates do not cover only the new `service` API change... But this big change served as a good prétexte to revise everything.

**Comment by JoelBender** [comment]
This is finished in #87 moved into `stage` and ready to be released.
