### ISSUE TITLE
Sample - ReadPropertyMultiple / Needs global definition in Python 3

### ISSUE THREAD

**Issue by ChristianTremblay** [JoelBender/bacpypes#88]
New version uses a main function that breaks the usage of globals

**Comment by JoelBender** [comment]
I worked on the rest of the sample applications as I noted in #89, and the `issue-88` has been merged into `stage` for additional testing.  Please checkout the `stage` branch and run the samples when you get a chance.

**Comment by ChristianTremblay** [comment]
Closing this for now. Will open issue if other bugs found in samples
